### ISSUE TITLE
prompt_module shows wrong string ('$') when root

### ISSUE THREAD

**Issue by furquan-lp** [chris-marsh/pureline#1]
The default `prompt_module` still shows the dollar sign when root [which is not the standard behavior](https://en.wikibooks.org/wiki/Guide_to_Unix/Explanations/Shell_Prompt#Root_shell_prompt).

Example:
```
 22:14  furquan@debian-home  ~  $  su
Password: 
 22:16  root@debian-home  /home/furquan  $  
```

**Comment by chris-marsh** [comment]
Thanks for the pr and fix.
Following form with '#' hadn't occured to me, I tend to mostly use sudo and my root accounts are left as default.

**Comment by chris-marsh** [comment]
Merged, so going to mark as closed.
