### ISSUE TITLE
Config file argument needs to be quoted

### ISSUE THREAD

**Issue by jchoksi-whitbread** [chris-marsh/pureline#15]
Hi

If a config file is provided as an argument and the path to the config file has a space in it, the sourcing of it fails.

https://github.com/chris-marsh/pureline/blob/318458905453de42b6c57df0a49c7871ee150afe/pureline#L385

regards,
Jinesh

**Comment by chris-marsh** [comment]
Thanks. I'll have this fixed soon. Planning to tidy up all the changes within the WIP branch and move them to master. I will include this bug fix.

**Comment by chris-marsh** [comment]
Fixed. Thanks again.
