### ISSUE TITLE
SSH module?

### ISSUE THREAD

**Issue by thatso** [chris-marsh/pureline#20]
I fail to understand how the SSH module is supposed to work.
If I SSH into another machine, I simply see the plain shell prompt of that machine - without any of the fancy pureline modifications. What am I missing?

Similarly, the root module seems to do nothing. As soon as I issue SU, the shell reverts to the standard prompt.

Am I supposed to additionally install pureline on the servers I SSH into and for the root account itself respectively?

Sorry for sounding dumb. I'm familiar with bash, but never played around much with command line prompt customization.

**Comment by chris-marsh** [comment]
To see PureLine on your SSH client, you are correct that you need to have it installed there. The same with su, you would need to have a PureLine prompt configured for root.

**Comment by thatso** [comment]
Thanks for the clarification. So my thinking was right.
Happily closing this issue now and thank you again for the fast answer.
