### ISSUE TITLE
Fix: BAT1 not working

### ISSUE THREAD

**Issue by thatso** [chris-marsh/pureline#21]
I don't know yet how to make a pull request.
However, I just recognized that the battery module throws up _path not found_ errors for BAT1 because of a typo in the file pureline/pureline in line 274:

`batt_dir=$batt_dir1""`

should read:

`batt_dir=$batt_dir"1"`

**Comment by chris-marsh** [comment]
Nice catch, thanks for the report. I'll push a fix through soon.
