### ISSUE TITLE
Issue when ssh-ing to a macOS with pureline

### ISSUE THREAD

**Issue by i-need-to-tell-you-something** [chris-marsh/pureline#34]
When I ssh to a macOS machine which has pureline configured, I get the following error message after every single command:

```
-bash: ip: command not found
```

This doesn't seem to affect anything as far as I can notice. The workaround is to install `ip` on OS X as described [here](https://superuser.com/questions/687310/ip-command-in-mac-os-x-terminal):

```bash
brew install iproute2mac
```

I'm not expecting a fix, but wanted to at least share the workaround where everyone encountering the problem might look for it first.

**Comment by chris-marsh** [comment]
Thanks for bringing this up. I should maybe add this to the readme as dependency for the user and ssh modules.

**Comment by chris-marsh** [comment]
I don't have access to macOS, but googling shows that ```ifconfig``` is still the default preferred command while linux has mostly moved to ```ip```.  I think the helper function to get the ip address should check which command is available and act accordingly.

I will put something together for tersting this.

**Comment by chris-marsh** [comment]
Addressed with commit https://github.com/chris-marsh/pureline/commit/466728704e96df2eac2fc961f9ae0b95f62ebc41.
