### ISSUE TITLE
Return code module - Output not displayed

### ISSUE THREAD

**Issue by briandu106** [chris-marsh/pureline#36]
Hi,

The return code module does not display output on CentOS7 and RHEL8 with bash versions 4.2.46(2) and 4.4.19(1) respectively.
![CentOS7_Capture](https://user-images.githubusercontent.com/35125576/66168240-3845e400-e699-11e9-81f9-ac5201d24c04.PNG)
![RHEL8_Capture](https://user-images.githubusercontent.com/35125576/66168248-3d0a9800-e699-11e9-887e-e3bbaa6de9ce.PNG)

But it displays output properly on Bash on Ubuntu on Windows (WSL) with bash version 4.4.20(1)
![WSL](https://user-images.githubusercontent.com/35125576/66168257-4431a600-e699-11e9-8cbf-7f4e069a131b.PNG)

Is this a known issue?

Thanks guys.

**Comment by chris-marsh** [comment]
Hi, sorry for not being around for a while and taking an age to reply!

That is odd. If you are still using pureline, is this still an issue? if so can you post the full config file where you have the issue?

**Comment by chris-marsh** [comment]
I've installed a CentOs container and can confirm this issue still exists.

**Comment by chris-marsh** [comment]
Resolved :)

![Screenshot_2021-02-18_22-09-08](https://user-images.githubusercontent.com/10662234/108428125-0275b100-7236-11eb-8739-b2c03e0afdcb.png)
