### ISSUE TITLE
Needed different symbol for SSH with Hack font on MacOS

### ISSUE THREAD

**Issue by andresrinivasan** [chris-marsh/pureline#38]
I was getting the square box with the SSH module. I had to update `PL_SYMBOLS[ssh]` in my local .pureline from `ef 84 89 20` to `f0 9d 94 96`.

See tail of attached [.pureline](https://github.com/chris-marsh/pureline/files/3871073/dot-pureline.txt)

**Comment by chris-marsh** [comment]
Hi, I think the config file is the perfect place to fix issues like this.
