### ISSUE TITLE
gnome-terminal tab title broken

### ISSUE THREAD

**Issue by skebanga** [chris-marsh/pureline#4]
```cpp
PROMPT_COMMAND=pureline_ps1
```

Setting the `PROMPT_COMMAND` to the result of `pureline_ps1` doesn't work for gnome-terminal

**Comment by chris-marsh** [comment]
I've just tested with gnome-terminal and it works fine for me. Your choice of terminal app should not have any effect on your bash PROMPT_COMMAND.


Can you give more detail? Do you get any error messages in your terminal? Can you cd to the ```
directory with the  pureline file and type:
```
source ./pureline
```

and let use know what happens and what output you get?

**Comment by skebanga** [comment]
Output of `source ./pureline`:

![image](https://user-images.githubusercontent.com/6157939/34958551-70f60c4e-fa00-11e7-9547-5a21329af945.png)

Notice that the title bar just has `"Terminal"` in it.

If I now change `PROMPT_COMMAND` as follows:

```
export PROMPT_COMMAND='printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/~}"'
```

Notice now that the title has changed to show username, hostname and cwd:

![image](https://user-images.githubusercontent.com/6157939/34958582-8cb7f096-fa00-11e7-996f-2fb4a7768b71.png)

If I change directory, the title changes accordingly

![image](https://user-images.githubusercontent.com/6157939/34958591-9449b4ca-fa00-11e7-9860-a83487d92680.png)

If I undo the manual setting of `PROMPT_COMMAND` I did above, so that I get the pureline `PROMPT_COMMAND`, you can see the `PS1` prompt updates (notice the sudden appearance of the red lock to signal read-only) when I change directory to `/usr/local/bin`, but the window's title no longer updates.

![image](https://user-images.githubusercontent.com/6157939/34958626-bae6ce10-fa00-11e7-9bc4-d4a5effca51e.png)

**Comment by skebanga** [comment]
Actually, through taking you through all these steps, I realised that the title is set to STDOUT of the result of executing `${PROMT_COMMAND}`

So whilst `pureline_ps1` sets the `PS1` variable, I can also have the title set by adding a `printf` call at the end

```
function pureline_ps1 {

	...
	PS1+=...
	...

	printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/~}"
}
```

Obviously the `printf` statement I've shown here is hardcoded, and a better approach would be to loop over your modules.

My bashfu isn't good enough to figure that out just yet.

**Comment by chris-marsh** [comment]
I see the issue. I wasn't aware as I don't use window decorations. This is happening because pureline overwrites the PROMPT_COMMAND. This was an intentional change due to feedback. I might look to change this or find an alternative. Anyway ... the quick fix is to change the last line of pureline from;

``PROMPT_COMMAND=pureline_ps1``
to
``PROMPT_COMMAND="pureline_ps1; $PROMPT_COMMAND"``

This appends your default setting after pureline.

**Comment by skebanga** [comment]
Thanks Chris

**Comment by chris-marsh** [comment]
I've pushed this change. Hopefully the issue is now resolved?
