### ISSUE TITLE
Unicode symbols

### ISSUE THREAD

**Issue by Terkea** [chris-marsh/pureline#44]
Hi folks, I've got a problem with the Unicode symbols, for some reason they decided not to show up
![image](https://user-images.githubusercontent.com/11928943/78682836-6a552e80-78e6-11ea-938f-d8550c941a4e.png)

**Comment by lynxhug** [comment]
You probably need to install powerline fonts? Here https://github.com/powerline/fonts

**Comment by Terkea** [comment]
indeed I did but still, that doesn't fix the missing icons but the triangles at the end of each colour

**Comment by lynxhug** [comment]
Then there is probably something wrong with your fonts configuration. I had same problem, installing fonts and following instructions from documentation helped me fix supposedly same problem. You could try out nerd fonts they have nice "triangles" icons from powerline-extra-symbols repo.

**Comment by chris-marsh** [comment]
Hi Terkea, can I confirm that after installing the font you have also configured your terminal to use it?
Which font have you installed and configured?

**Comment by chris-marsh** [comment]
Closing, as without further information this appears to be a system configuration issue and not PureLine related.
