### ISSUE TITLE
Right align segments

### ISSUE THREAD

**Issue by rashil2000** [chris-marsh/pureline#58]
How do I configure a segment (like time, battery) to get aligned to the right side of terminal?

**Comment by chris-marsh** [comment]
Unfortunately this isn't possible yet. It was mentioned recently in issue https://github.com/chris-marsh/pureline/issues/32. I'm currently making a lot of changes in the [dev](https://github.com/chris-marsh/pureline/tree/dev) branch which are nearly complete. Once this is pushed to main I'll look into right aligning.
