### ISSUE TITLE
Cursor jumps back three characters when wrapping the first line

### ISSUE THREAD

**Issue by mad-ady** [chris-marsh/pureline#61]
Hello,
I'm using the latest git pureline version, with this config: https://paste.ubuntu.com/p/cntRQbNmmX/

I have a weird behavior that can be visually seen in this video: https://youtu.be/U4UlqufYGAg

Any ideas where to look for clues?
My terminal is xfce4-term, on a Ubuntu 20.04 system.

**Comment by mad-ady** [comment]
If it helps, a similar recording done with asciinema doesn't show the characters at all: https://asciinema.org/a/a6L8kFACPNe2IBR6lplGUcbEp

**Comment by chris-marsh** [comment]
Thanks for the videos, thats a great help to try and diagnose the issue.
So ... the recording and playback on asciinema is correct. Although while recording in your own terminal you see the cursor issues when wrapping?

**Comment by mad-ady** [comment]
Yes, I thought a video is worth 1024 words...

Asciinema doesn't render at all the overlapped (overwritten) characters.
You can see that the new line has fewer characters than what's echoed back.
I initially tried using it to do the recording, but the playback differed
from what I was seeing.

**Comment by chris-marsh** [comment]
I'm wondering if the '$' symbol in the prompt needs to be escaped. I dont see any difference on my system, but to check, could you disable the prompt module and see if the issue goes away/reduces/changes?

**Comment by mad-ady** [comment]
You were right - I commented out:
#    'prompt_module          MyDarkGrey  White'
and the issue went away.

Is there anything I can do to fix it via configuration?

**Comment by mad-ady** [comment]
I've tested as root and the prompt_module (# in this case) does not cause
the cursor to jump back - so only $ causes the issue:
```
 root  💻 frost  ~  #  echo 1234567890 1234567890 1234567890 1234567890
1234
567890
1234567890 1234567890 1234567890 1234567890 1234567890
```

**Comment by chris-marsh** [comment]
I've pushed a fix, escaping the $ into main. Hopefully this resolves the issue?

**Comment by mad-ady** [comment]
Thank you. I have updated my pureline install and so far the issue doesn't
reproduce anymore!
Cheers!
