### ISSUE TITLE
Running on a Pi (bash version 5.0.3)

### ISSUE THREAD

**Issue by jason-a69** [chris-marsh/pureline#79]
Hi there,

I am having problems getting this going on a Pi, this is the error I am getting

```
-bash: PROMPT_COMMAND: line 0: syntax error near unexpected token `;'
-bash: PROMPT_COMMAND: line 0: `pureline_pre; [[ -w '/tmp/dietpi-process.pid' ]] && rm -f /tmp/dietpi-process.pid &> /dev/null && echo -ne '\r\e[J'; ; pureline_ps1;'
```

It is odd because it works fine on Pop OS (bash version 5.1.16) and Debian 11 (bash version 5.1.4).

If you want me to test any code changes then I am happy to do so, I tried to debug the problem myself but I could not get it working.

Many thanks

Jason

**Comment by chris-marsh** [comment]
What version of bash is dietpi running?

**Comment by chris-marsh** [comment]
Actually i can see the issue in the generated PS1 you posted and the error message of the unexpected semi-colon.  I'll investigate it some more. Seems pureline hasn't appended cleanly to the existing PS1. I'll investigate this some more.

**Comment by CyrilOtheninGirard** [comment]
Pull request [#72](https://github.com/chris-marsh/pureline/pull/72) has been merged. 
It should solve your issue.

**Comment by jason-a69** [comment]
This is now working, thanks everyone for your help
