### ISSUE TITLE
Merging PR #66 reintroduced a bug in __pureline_pre

### ISSUE THREAD

**Issue by CyrilOtheninGirard** [chris-marsh/pureline#84]
2 days ago, merging PR #66 "Allowing TMUX pane titles to persist" reintroduced this bug that I fixed in merged PR #72 "Fixes when inherited PROMPT_COMMAND is not empty" : 
> [FIX-1]
> function 'pureline_pre' now returns the saved error code of the last executed command.
> => Does not break an inherited PROMPT_COMMAND that requires that value.

Please merge #83 "Don't set the GUI window title if PL_TITLEBAR is empty" to cleanly solve that issue.

**Comment by chris-marsh** [comment]
Thanks Cyril. Done.
