### ISSUE TITLE
Adding a \n before the prompt IS A FUCKING NIGHTMARE

### ISSUE THREAD

**Issue by Chiarchiaooo** [chris-marsh/pureline#88]
Hi, i've been sitting here for the last HALF A FUCKING HOUR, trying to add a fucking \n before your command prompt.
I'VE TRIED EVERYTHING, but nothing seems to work. Right now my terminal has the same utility of Windows troubleshooter

Please HELP

**Comment by chris-marsh** [comment]
Sorry its taken me 3 months to reply ... i've not been around much recently.
But ... to add a '\n' you can use the "newline" segment in your config. eg ...
`PL_SEGMENTS=('newline' 'time' 'path' 'prompt')`
Does this help?

**Comment by Chiarchiaooo** [comment]
Dude, thx for the reply, but I don't need it anymore.
