### ISSUE TITLE
Doesn't work on macOS

### ISSUE THREAD

**Issue by nmajin** [chris-marsh/pureline#9]
Your ../pureline/pureline config declares dictionaries in bash with -A, so this doesn't work and even after correcting this the display looks like this:

<img width="481" alt="screen shot 2018-04-12 at 9 14 39 pm" src="https://user-images.githubusercontent.com/253669/38711923-8dfd5862-3e96-11e8-8e1f-df3e9c52928a.png">

I even configured a Powerline font thinking that could be the issue but no luck.

**Comment by chris-marsh** [comment]
I think the associative arrays were introduced in bash v4, put it sounds like your having other issues too. Can we first establish which version of bash you are running/being evoked by pureline?

`/bin/env bash --version`

**Comment by nmajin** [comment]
Yea, the issue I am really having at this point appears to be the theme/color/etc/ not working.

~/Downloads $ /bin/env bash --version
-bash: /bin/env: No such file or directory
~/Downloads $ /bin/bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)
Copyright (C) 2007 Free Software Foundation, Inc.

**Comment by chris-marsh** [comment]
I'm on linux with bash 4.4.19, but have have compiled bash 3.2.57 to test and I can confirm similar results. An easy fix would be to upgrade bash with homebrew, but thats probably an excessive solution to get a nice prompt :-)

I'll play around with it and see how it goes.

**Comment by jchoksi-whitbread** [comment]
@ajdegol Indeed. I've tested a number of powerline prompt clones and tried to make my own one as well and I found Chris's prompt to be the best one so far. The code is modular and easy to understand / extend.

**Comment by msantoro12** [comment]
I would also love to see a mac compatible version. Upgrading bash in a corporate environment isn't very safe or plausible.

**Comment by amcgregor** [comment]
As a note, [Zsh is becoming the default shell for macOS](https://support.apple.com/en-us/HT208050) as of Catalina.  BASH itself is "widely compatible", but absolutely ancient on macOS.

**Comment by chris-marsh** [comment]
Closing as bash can be upgraded on macos.
